version: "3.9"

services:
  backend:
    image: "upml-elections-backend-image"
    container_name: "upml-elections-backend"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - "upml-elections-volume:/app/db"
      - "upml-elections-volume:/app/images"
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DB_PATH: /app/db/database.sqlite

  frontend:
    image: "upml-elections-frontend-image"
    container_name: "upml-elections-frontend"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:4000"

volumes:
  upml-elections-volume:
