version: "3.9"

services:
  backend:
    image: "upml-elections-backend-image"
    container_name: "upml-elections-backend"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - "upml-elections-volume:/app/db"
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

volumes:
  upml-elections-volume:
